# Generated by Django 4.2.23 on 2025-11-03 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251029_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=datetime.date(2025, 11, 3)),
            preserve_default=False,
        ),
    ]
