# Generated by Django 4.2.23 on 2025-11-06 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_slot_end_time_alter_slot_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='date',
        ),
    ]
