# Generated by Django 4.2.7 on 2025-11-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('mentor', 'date', 'start_time', 'end_time')},
        ),
    ]
